# Generated by Django 3.2.16 on 2022-10-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationtracker', '0002_auto_20221010_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='Nalco colony', max_length=250),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Bhubaneswar', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name_of_vaccination',
            field=models.CharField(default='covaxin', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(default='Odisha', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vaccination_date',
            field=models.CharField(default='08-10-2022', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zip',
            field=models.IntegerField(default=751023),
        ),
    ]
