# Generated by Django 3.2.16 on 2022-10-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationtracker', '0003_auto_20221010_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_school_coordinator',
            field=models.BooleanField(default=True),
        ),
    ]
