# Generated by Django 3.2.16 on 2022-10-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationtracker', '0004_alter_customuser_is_school_coordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_school_coordinator',
            field=models.BooleanField(default=False),
        ),
    ]
