# Generated by Django 3.2.16 on 2022-10-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationtracker', '0005_alter_customuser_is_school_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationdrive',
            name='is_slote_done',
            field=models.BooleanField(default=False),
        ),
    ]
