# Generated by Django 3.2.16 on 2022-10-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccinationtracker', '0006_vaccinationdrive_is_slote_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationdrive',
            name='date',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
